# Import libraries

In [49]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statistics
from scipy.stats import mode
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Import dataset

In [50]:
dataset = pd.read_csv('iris_dataset.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# kNN

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [53]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [54]:
print(classifier.predict(sc.transform([[6, 2.9, 4.5, 1.5]])))

['versicolor']


In [55]:
y_pred = classifier.predict(X_test)

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


0.9666666666666667

In [57]:
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, average = 'macro'))
print(precision_score(y_test, y_pred, average = 'micro'))
print(precision_score(y_test, y_pred, average = 'weighted'))
print(recall_score(y_test, y_pred, average = 'macro'))
print(recall_score(y_test, y_pred, average = 'micro'))
print(recall_score(y_test, y_pred, average = 'weighted'))

0.9666666666666667
0.9761904761904763
0.9666666666666667
0.9690476190476189
0.9444444444444445
0.9666666666666667
0.9666666666666667


# Naive Bayes

In [58]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [60]:
print(classifier.predict(sc.transform([[6.1 , 2.9, 4.7, 1.4]])))

['virginica']


In [61]:
y_pred = classifier.predict(X_test)

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


0.9666666666666667

In [63]:
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, average = 'macro'))
print(precision_score(y_test, y_pred, average = 'micro'))
print(precision_score(y_test, y_pred, average = 'weighted'))
print(recall_score(y_test, y_pred, average = 'macro'))
print(recall_score(y_test, y_pred, average = 'micro'))
print(recall_score(y_test, y_pred, average = 'weighted'))

0.9666666666666667
0.9761904761904763
0.9666666666666667
0.9690476190476189
0.9444444444444445
0.9666666666666667
0.9666666666666667


# Decision Trees

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [65]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [70]:
print(classifier.predict(sc.transform([[6, 2.2, 4, 1]])))

['virginica']


In [67]:
y_pred = classifier.predict(X_test)

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


1.0

In [69]:
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, average = 'macro'))
print(precision_score(y_test, y_pred, average = 'micro'))
print(precision_score(y_test, y_pred, average = 'weighted'))
print(recall_score(y_test, y_pred, average = 'macro'))
print(recall_score(y_test, y_pred, average = 'micro'))
print(recall_score(y_test, y_pred, average = 'weighted'))

1.0
1.0
1.0
1.0
1.0
1.0
1.0
